---

- hosts: "{{host}}"
  vars:
    - virtenv_path: "{{zstack_root}}/virtualenv/virtualrouter/"
    - vr_root: "{{zstack_root}}/virtualrouter"
    - file_root: "files/virtualrouter"
    - pip_url: "{{pypi_url|default('https://pypi.python.org/simple/')}}"
    - proxy: "{{http_proxy|default()}}"
    - sproxy: "{{https_proxy|default()}}"
    - chroot_env: "{{chroot|default('false')}}"

  tasks:
    - include: zstacklib.yaml

    - name: create root directories
      shell: "mkdir -p {{item}}"
      with_items:
        - "{{vr_root}}"
        - "{{virtenv_path}}"

    - name: install virtual router related packages for RedHat
      yum: name=dnsmasq
      when: ansible_os_family == "RedHat"

    - name: install virtual router related packages for Debian
      apt: name=dnsmasq
      when: ansible_os_family == "Debian"

    - shell: pip --version | grep 7.0.3
      register: pip_ret
      ignore_errors: True

    - name: copy pip 7.0.3
      copy: src="files/pip-7.0.3.tar.gz" dest="{{zstack_root}}/pip-7.0.3.tar.gz"
      when: pip_ret.rc != 0

    - name: install pip 7.0.3
      pip: name="{{zstack_root}}/pip-7.0.3.tar.gz" extra_args="--ignore-installed"
      when: pip_ret.rc != 0

    - shell: virtualenv --version | grep "12.1.1"
      register: virtualenv_ret
      ignore_errors: True

    - name: install virtualenv
      pip: name=virtualenv version=12.1.1 extra_args="--ignore-installed --trusted-host {{trusted_host}} -i {{pip_url}}"
      when: virtualenv_ret.rc != 0

    - name: create virtualenv
      shell: "rm -rf {{virtenv_path}} &&  virtualenv {{virtenv_path}}"

    - name: create dnsmasq host dhcp file
      shell: /bin/touch /etc/hosts.dhcp

    - name: create dnsmasq host option file
      shell: /bin/touch /etc/hosts.option

    - name: create dnsmasq host dns file
      shell: /bin/touch /etc/hosts.dns

    - name: copy sysctl.conf
      copy: src="{{file_root}}/sysctl.conf" dest=/etc/sysctl.conf

    - name: copy dnsmasq conf file
      copy: src="{{file_root}}/dnsmasq.conf" dest=/etc/dnsmasq.conf
      notify:
        - restart dnsmasq

    - name: enable dnsmasq service
      service: name=dnsmasq enabled=yes state=started
      when: chroot_env == 'false'

    - name: copy zstacklib
      copy: src="files/zstacklib/{{pkg_zstacklib}}" dest="{{vr_root}}/{{pkg_zstacklib}}"
      notify:
        - install zstacklib
        - restart vr

    - name: copy virtual router
      copy: src="{{file_root}}/{{pkg_virtualrouter}}" dest="{{vr_root}}/{{pkg_virtualrouter}}"
      notify:
        - install vr
        - restart vr

    - name: copy virtual rourte service file
      copy: src="{{file_root}}/zstack-virtualrouter" dest=/etc/init.d/ mode=755
      notify:
        - restart vr

    - meta: flush_handlers

    - name: enable virtual router service for RedHat
      service: name=zstack-virtualrouter enabled=yes state=started
      when: chroot_env == 'false' and ansible_os_family == 'RedHat'

    - name: enable virtual router service for RedHat on chroot
      service: name=zstack-virtualrouter enabled=yes state=stopped
      when: chroot_env != 'false' and ansible_os_family == 'RedHat'

    - name: enable virtual rotuer service for Debian -1
      command: sed -i '/zstack-virtualrouter start/d' /etc/rc.local 
      when: ansible_os_family == 'Debian'

    - name: enable virtual rotuer service for Debian -2
      command: sed -i 's/^exit 0/\/etc\/init.d\/zstack-virtualrouter start\nexit 0/' /etc/rc.local
      when: ansible_os_family == 'Debian'

  handlers:
    - name: restart dnsmasq
      service: name=dnsmasq state=restarted enabled=yes
      when: chroot_env == 'false'

    - name: install zstacklib
      environment:
        http_proxy: "{{proxy}}"
        https_proxy: "{{sproxy}}"
      pip: name="{{vr_root}}/{{pkg_zstacklib}}" extra_args="--ignore-installed --trusted-host {{trusted_host}} -i {{pip_url}}" virtualenv="{{virtenv_path}}" virtualenv_site_packages=yes

    - name: install vr
      environment:
        http_proxy: "{{proxy}}"
        https_proxy: "{{sproxy}}"
      pip: name="{{vr_root}}/{{pkg_virtualrouter}}" extra_args="--ignore-installed --trusted-host {{trusted_host}} -i {{pip_url}}" virtualenv="{{virtenv_path}}"

    - name: restart vr
      service: name=zstack-virtualrouter enabled=yes state=restarted
      when: chroot_env == 'false' 
