---
- name: state epel.repo
  stat: path=/etc/yum.repos.d/epel.repo
  register: epel_repo

- name: install epel-release yum repo
  when: ansible_os_family == 'RedHat' and epel_repo.stat.exists != true
  copy: src=files/zstacklib/epel-release-source.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name: install epel-release
  when: ansible_os_family == 'RedHat' and epel_repo.stat.exists != true
  yum: name=epel-release
       enablerepo=epel-release-source
       state=present

- name: enable epel repository
  when: ansible_os_family == 'RedHat'
  ini_file: dest=/etc/yum.repos.d/epel.repo
            section=epel
            option=enabled
            value=1

- name: install dependency packages for RedHat based OS
  when: ansible_os_family == 'RedHat'
  yum: name="{{item}}"
  with_items:
    - python-devel
    - python-setuptools
    - python-pip
    - gcc
    - autoconf
    - libselinux-python

- name: install dependency packages for Debian based OS
  when: ansible_os_family == 'Debian'
  apt: pkg="{{item}}" update_cache=yes
  with_items:
    - python-dev
    - python-setuptools
    - python-pip
    - gcc
    - autoconf

- shell: pip --version | grep 7.0.3
  register: pip_ret
  ignore_errors: True

- name: make dir for copy pip
  shell: "mkdir -p {{zstack_root}}"
  when: pip_ret.rc != 0

- name: copy pip 7.0.3
  copy: src="files/pip-7.0.3.tar.gz" dest="{{zstack_root}}/pip-7.0.3.tar.gz"
  when: pip_ret.rc != 0

- name: install pip 7.0.3
  pip: name="{{zstack_root}}/pip-7.0.3.tar.gz" extra_args="--ignore-installed"
  when: pip_ret.rc != 0
