---
- name: set RHEL7 yum repo
  when: ansible_os_family == 'RedHat' and ansible_distribution_version >= '7'
  shell: echo -e "[zstack-local]\nname=ZStack Local Yum Repo\nbaseurl=http://{{yum_server}}/static/centos7_repo\nenabled=0\ngpgcheck=0\n" > /etc/yum.repos.d/zstack-local.repo

- name: set RHEL6 yum repo
  when: ansible_os_family == 'RedHat' and ansible_distribution_version >= '6' and ansible_distribution_version < '7'
  shell: echo -e "[zstack-local]\nname=ZStack Local Yum Repo\nbaseurl=http://{{yum_server}}/static/centos6_repo\nenabled=0\ngpgcheck=0\n" > /etc/yum.repos.d/zstack-local.repo

- name: install libselinux-python, since next step might use it.
  when: ansible_os_family == 'RedHat'
  shell: yum --disablerepo=* --enablerepo=zstack-local --nogpgcheck install -y  libselinux-python python-devel python-setuptools python-pip gcc autoconf

- name: install dependency packages for Debian based OS
  when: ansible_os_family == 'Debian'
  apt: pkg="{{item}}" update_cache=yes
  with_items:
    - python-dev
    - python-setuptools
    - python-pip
    - gcc
    - autoconf

- shell: pip --version | grep 7.0.3
  register: pip_ret
  ignore_errors: True

- name: make dir for copy pip
  shell: "mkdir -p {{zstack_root}}"
  when: pip_ret.rc != 0

- name: copy pip 7.0.3
  copy: src="files/pip-7.0.3.tar.gz" dest="{{zstack_root}}/pip-7.0.3.tar.gz"
  when: pip_ret.rc != 0

- name: install pip 7.0.3
  pip: name="{{zstack_root}}/pip-7.0.3.tar.gz" extra_args="--ignore-installed"
  when: pip_ret.rc != 0
