---

- name: install dependency packages for RedHat based OS
  when: ansible_os_family == 'RedHat'
  yum: name="{{item}}"
  with_items:
    - python-devel
    - python-setuptools
    - python-pip
    - gcc
    - autoconf
    - libselinux-python

- name: install dependency packages for Debian based OS
  when: ansible_os_family == 'Debian'
  apt: pkg="{{item}}" update_cache=yes
  with_items:
    - python-dev
    - python-setuptools
    - python-pip
    - gcc
    - autoconf

- shell: pip --version | grep 7.0.3
  register: pip_ret
  ignore_errors: True

- name: make dir for copy pip
  shell: "mkdir -p {{zstack_root}}"
  when: pip_ret.rc != 0

- name: copy pip 7.0.3
  copy: src="files/pip-7.0.3.tar.gz" dest="{{zstack_root}}/pip-7.0.3.tar.gz"
  when: pip_ret.rc != 0

- name: install pip 7.0.3
  pip: name="{{zstack_root}}/pip-7.0.3.tar.gz" extra_args="--ignore-installed"
  when: pip_ret.rc != 0
